	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, GRAY, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, GRAY
	tilepal 0, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, WATER, BROWN
	tilepal 0, BROWN, BROWN, GRAY, BROWN, BROWN, GRAY, GRAY, WATER
	tilepal 0, GRAY, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GREEN, GREEN
	tilepal 1, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY
