	tilepal 0, WATER, GRAY, GRAY, GRAY, RED, GREEN, GREEN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, GREEN, GREEN, BROWN
	tilepal 0, BROWN, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, BROWN, ROOF
	tilepal 0, ROOF, YELLOW, BROWN, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, BROWN, BROWN, GRAY, BROWN, BROWN, RED
	tilepal 0, RED, GRAY, ROOF, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal 0, ROOF, GRAY, ROOF, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, BROWN, BROWN, GRAY
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
