	tilepal 0, GRAY, GRAY, GRAY, RED, GRAY, WATER, RED, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, YELLOW, BROWN, RED, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY
	tilepal 0, WATER, WATER, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 0, YELLOW, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, WATER, WATER, GRAY, GRAY, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, BROWN, YELLOW, BROWN, RED, RED, WATER, GRAY
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, RED, BROWN, BROWN
	tilepal 0, GREEN, GREEN, WATER, WATER, ROOF, GRAY, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, WATER, WATER, ROOF, TEXT
