	tilepal 0, WATER, GRAY, GRAY, GRAY, RED, GRAY, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, GRAY, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, RED, WATER, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, ROOF, ROOF, BROWN, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, WATER, BROWN, BROWN, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, WATER, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, RED, BROWN, BROWN, TEXT
