	tilepal 0, WATER, GRAY, GRAY, GRAY, RED, GRAY, WATER, WATER
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GRAY, RED, GRAY, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, RED, WATER, WATER, ROOF, BROWN, BROWN
	tilepal 0, ROOF, BROWN, GREEN, GREEN, ROOF, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, WATER, ROOF, BROWN, ROOF
	tilepal 0, ROOF, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, WATER, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER

rept 32
	db $ff
endr

	tilepal 1, RED, BROWN, BROWN