	tilepal 0, GRAY, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, GRAY, GRAY, WATER, WATER, GRAY, GRAY, WATER
	tilepal 0, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, WATER, WATER, GRAY, ROOF, WATER
	tilepal 0, WATER, WATER, WATER, GRAY, GRAY, WATER, WATER, GRAY
	tilepal 0, GRAY, WATER, WATER, WATER, WATER, GRAY, ROOF, WATER
	tilepal 0, ROOF, ROOF, WATER, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, WATER, WATER, WATER, WATER, GRAY, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, BROWN, BROWN, WATER, WATER, WATER, WATER
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, WATER
	tilepal 1, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, ROOF, ROOF
	tilepal 1, ROOF, ROOF
