	tilepal 0, GRAY, GRAY, WATER, WATER, BROWN, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, BROWN, ROOF, RED, RED, RED
	tilepal 0, ROOF, WATER, ROOF, ROOF, WATER, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, WATER, ROOF, RED, RED, RED
	tilepal 0, ROOF, ROOF, WATER, BROWN, RED, WATER, WATER, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, ROOF, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, WATER, WATER, RED, GRAY, BROWN, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, RED, RED, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, BROWN, BROWN, RED, RED, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, WATER, WATER, GRAY, GRAY, BROWN, BROWN
	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
