	tilepal 0, GRAY, BROWN, BROWN, ROOF, GRAY, ROOF, ROOF, GREEN
	tilepal 0, GREEN, BROWN, BROWN, YELLOW, YELLOW, ROOF, ROOF, ROOF
	tilepal 0, GRAY, BROWN, GRAY, BROWN, WATER, ROOF, ROOF, GREEN
	tilepal 0, GREEN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, GRAY, BROWN, GRAY, GRAY, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GREEN, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, BROWN, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, GRAY, GRAY
	tilepal 0, GRAY, GRAY, ROOF, BROWN, ROOF, ROOF
