	tilepal 0, GRAY, RED, GRAY, WATER, WATER, WATER, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal 0, GRAY, RED, RED, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, GRAY, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, GRAY, WATER, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, GRAY, RED, RED, GRAY
	tilepal 0, RED, RED, RED, RED, RED, RED, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, YELLOW, YELLOW
	tilepal 1, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, YELLOW, YELLOW
	tilepal 1, WATER, WATER, ROOF, GRAY, GRAY, GRAY, RED, RED
	tilepal 1, RED, RED, WATER, WATER, WATER, WATER, WATER, GRAY
	tilepal 1, WATER, WATER, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 1, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
