	tilepal 0, WATER, GRAY, GRAY, GRAY, RED, GRAY, WATER, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, GRAY, WATER, WATER
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, ROOF
	tilepal 0, WATER, WATER, GRAY, GRAY, GREEN, GREEN, ROOF, ROOF
	tilepal 0, WATER, WATER, BROWN, GRAY, GRAY, GRAY, GRAY