	object_const_def
	const POKEMONTOWER1F_RECEPTIONIST
	const POKEMONTOWER1F_MIDDLE_AGED_WOMAN
	const POKEMONTOWER1F_BALDING_GUY
	const POKEMONTOWER1F_GIRL
	const POKEMONTOWER1F_CHANNELER

PokemonTower1F_MapScripts:
	def_scene_scripts

	def_callbacks

PokemonTower1F_MapEvents:
	db 0, 0 ; filler

	def_warp_events
	warp_event 10, 17, LAVENDER_TOWN, 6;2
	warp_event 11, 17, LAVENDER_TOWN, 6;2
	; warp_event 18,  9, POKEMON_TOWER_2F, 2

	def_coord_events

	def_bg_events

	def_object_events
	; object_event  2,  3, SPRITE_GRANNY, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, PAL_NPC_RED, OBJECTTYPE_SCRIPT, 0, SeerScript, -1
	
	; object_event 15, 13, SPRITE_LINK_RECEPTIONIST, STAY, UP, TEXT_POKEMONTOWER1F_RECEPTIONIST
	; object_event  6,  8, SPRITE_MIDDLE_AGED_WOMAN, STAY, NONE, TEXT_POKEMONTOWER1F_MIDDLE_AGED_WOMAN
	; object_event  8, 12, SPRITE_BALDING_GUY, STAY, NONE, TEXT_POKEMONTOWER1F_BALDING_GUY
	; object_event 13,  7, SPRITE_GIRL, STAY, NONE, TEXT_POKEMONTOWER1F_GIRL
	; object_event 17,  7, SPRITE_CHANNELER, STAY, LEFT, TEXT_POKEMONTOWER1F_CHANNELER
